Namespace Web.Handlers

	''' <summary></summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>03/02/2014 13:10:49</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Athena\Athena\_Web\_Handlers\_Generated\RedirectHandler.tt</generator-source>
	''' <generator-template>Text-Templates\Classes\VB_Object.tt</generator-template>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Athena\Athena\_Web\_Handlers\_Generated\RedirectHandler.tt", "1")> _
	Partial Public Class RedirectHandler
		Inherits System.Object
		Implements System.Web.IHttpHandler

		#Region " Public Constructors "

			''' <summary>Default Constructor</summary>
			Public Sub New()

				MyBase.New()

				m_Url = System.Configuration.ConfigurationManager.AppSettings("Athena.Url")
			End Sub

			''' <summary>Parametered Constructor (1 Parameters)</summary>
			Public Sub New( _
				ByVal _Url As System.String _
			)

				MyBase.New()

				Url = _Url

			End Sub

		#End Region

		#Region " Class Plumbing/Interface Code "

			#Region " DbConsumer Implementation "

				''' <summary>Configuration Key Name for DB</summary>
				''' <remarks></remarks>
				Public Const CONFIGURATION_DB_MAIN As String = "DB.Athena"

				''' <summary>Internal Reference to DB Connection Object</summary>
				''' <remarks></remarks>
				Private _DB As System.Data.SqlClient.SqlConnection = New System.Data.SqlClient.SqlConnection(System.Configuration.ConfigurationManager.ConnectionStrings(CONFIGURATION_DB_MAIN).ConnectionString())

				''' <summary>DB Connection Object</summary>
				''' <remarks></remarks>
				Public ReadOnly Property DB() As System.Data.IDbConnection
					Get
						Return _DB
					End Get
				End Property

			#End Region

			#Region " IHttpHandler Implementation "

				#Region " Public Properties "

					''' <summary>Is Reusable Implementation for IHttpHandler</summary>
					''' <remarks></remarks>
					Public ReadOnly Property IHttpHandler_IsReusable() As System.Boolean Implements System.Web.IHttpHandler.IsReusable
						Get
							Return True
						End Get
					End Property

				#End Region

				#Region " Public Shared Query String Constants "

					''' <summary>Constant for Query String Parameter: Instance</summary>
					''' <remarks></remarks>
					Public Const QUERY_INSTANCE As String = "i"

					''' <summary>Constant for Query String Parameter: Event</summary>
					''' <remarks></remarks>
					Public Const QUERY_EVENT As String = "e"

					''' <summary>Constant for Query String Parameter: Redirect</summary>
					''' <remarks></remarks>
					Public Const QUERY_REDIRECT As String = "r"

				#End Region

			#End Region

		#End Region

		#Region " Public Constants "

			''' <summary>Public Shared Reference to the Name of the Property: Url</summary>
			''' <remarks></remarks>
			Public Const PROPERTY_URL As String = "Url"

		#End Region

		#Region " Private Variables "

			''' <summary>Private Data Storage Variable for Property: Url</summary>
			''' <remarks></remarks>
			Private m_Url As System.String

		#End Region

		#Region " Public Properties "

			''' <summary>Provides Access to the Property: Url</summary>
			''' <remarks></remarks>
			Public Property Url() As System.String
				Get
					Return m_Url
				End Get
				Set(value As System.String)
					m_Url = value
				End Set
			End Property

		#End Region

	End Class

End Namespace