Namespace Core

	''' <summary>Enum Representing Athena Object Types</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>03/02/2014 13:06:46</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Athena\Athena\_Core\Enums\ObjectType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Athena\Athena\_Core\Enums\ObjectType.tt", "1")> _
	Public Enum ObjectType As System.Int32

		''' <summary>Exercise</summary>
		Exercise = 1

		''' <summary>Event</summary>
		[Event] = 2

		''' <summary>Option</summary>
		[Option] = 3

		''' <summary>Instance</summary>
		Instance = 4

	End Enum

End Namespace