Namespace Core

	''' <summary>Enum Representing Athena Analysis Span Types</summary>
	''' <autogenerated>Generated from a T4 template. Modifications will be lost, if applicable use a partial class instead.</autogenerated>
	''' <generator-date>03/02/2014 13:06:47</generator-date>
	''' <generator-functions>1</generator-functions>
	''' <generator-source>Athena\Athena\_Core\Enums\SpanType.tt</generator-source>
	''' <generator-version>1</generator-version>
	<System.CodeDom.Compiler.GeneratedCode("Athena\Athena\_Core\Enums\SpanType.tt", "1")> _
	Public Enum SpanType As System.Int32

		''' <summary>Ticks</summary>
		Ticks = 1

		''' <summary>Milliseconds</summary>
		Milliseconds = 2

		''' <summary>Seconds</summary>
		Seconds = 3

		''' <summary>Minutes</summary>
		Minutes = 4

		''' <summary>Hours</summary>
		Hours = 5

		''' <summary>Days</summary>
		Days = 6

	End Enum

End Namespace